### ISSUE TITLE
[Epic] Docker-build Provider 

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-docker#963]
### Documents 
[Docker-Build Provider PRFAQ](https://docs.google.com/document/d/1cbZvk3yE-nnBEaeh_5cWulB3Z7MGPuugZqqLgGv0nug/edit#heading=h.xqlkvx6h7y2p) 
[Docker-Build Provider Name Decision](https://docs.google.com/document/d/1M8_q60BseZ-gM1PK59rbuQJTPhhOczp4ya5BVMo-BRw/edit#heading=h.l9sv3n5afcqg) 

```[tasklist]
## GTM Items
- [x] Finalize New Docker Provider Name - 04/10
- [x] Engineering Work Complete - ECD 04/19
- [x] [Social Media Messaging](https://docs.google.com/document/d/1oXeAcrZgAjUrVv0DvRXZiqrlPKdA0bz_s4mKakvX0Sk/edit#heading=h.44wf0q4plj0i) - ECD 04/19
- [x] [Introduction Blog hosted by Pulumi ](https://github.com/pulumi/pulumi-hugo/pull/4211) - ECD 04/22
- [x] Intro Blog Review by SMEs - ECD 04/23
- [x] Publish the provider to the registry - 04/23
- [x] Close out all open issues in the docker provider - ECD 04/24
- [x] Post Blogs - 04/25 11.30AM ET
- [x] Post Socials - 04/25 (scheduled - ready to go) 12.15PM ET
- [ ] Joint Workshop Planned for June/July (ECD TBD) - NOT PRIORITIZED for 04/25
- [ ] Introduction Blog hosted by Docker (ECD Target Week of 05/14) - NOT PRIORITIZED for 04/25
```

Prototype and test a buildx based Image resource. 

```[tasklist]
- [ ] https://github.com/pulumi/pulumi-docker/issues/884
- [ ] https://github.com/pulumi/pulumi-docker/issues/958
- [ ] https://github.com/pulumi/pulumi-docker/issues/885
- [ ] https://github.com/pulumi/pulumi-docker/issues/887
- [ ] https://github.com/pulumi/pulumi-docker/issues/888
- [ ] https://github.com/pulumi/pulumi-docker/issues/886
- [ ] https://github.com/pulumi/pulumi-docker/issues/964
- [ ] https://github.com/pulumi/pulumi-docker/issues/965
- [ ] https://github.com/pulumi/pulumi-docker/issues/966
- [ ] https://github.com/pulumi/pulumi-docker/issues/969
- [ ] https://github.com/pulumi/pulumi-docker/issues/959
- [ ] https://github.com/pulumi/pulumi-docker/issues/970
- [ ] https://github.com/pulumi/pulumi-docker/issues/1026
- [ ] https://github.com/pulumi/pulumi-docker/issues/889
```

Internal: [buildx.Image details](https://docs.google.com/document/d/1CSfmZvP3VV5NDVLpyNT2-3qa2gmJLk-QXGxgIHiPwI4/edit#heading=h.vwiwvg1zly8y)
```[tasklist]
### Docker issues to be closed when docker-build ships
- [ ] https://github.com/pulumi/pulumi-docker/issues/296
- [ ] https://github.com/pulumi/pulumi-docker/issues/424
- [ ] https://github.com/pulumi/pulumi-docker/issues/271
- [ ] https://github.com/pulumi/pulumi-docker/issues/979
- [ ] https://github.com/pulumi/pulumi-docker/issues/666
- [ ] https://github.com/pulumi/pulumi-docker/issues/835
- [ ] https://github.com/pulumi/pulumi-docker/issues/539
- [ ] https://github.com/pulumi/pulumi-docker/issues/497
- [ ] https://github.com/pulumi/pulumi-docker/issues/971
- [ ] https://github.com/pulumi/pulumi-docker/issues/956
- [ ] https://github.com/pulumi/pulumi-docker/issues/761
- [ ] https://github.com/pulumi/pulumi-docker/issues/713
```
